import {createSlice, nanoid } from '@reduxjs/toolkit';


const initialState = {
    todos: [{id: 1, text: "Hello world"}],  //tumhare slice ka default data jab app start hota hai.Ye decides karta hai state ka shape (structure).Tum jo state store karna chahte ho uska structure initialState me define karo.Ye structure decide karega ki reducer functions me tum state ko kaise handle karoge.
    //Tum initialState ko ek default data / dummy content samajh lo,Aur reducers ke andar banaya hua todo = user ke action se create hone wala real data.

    //Dummy data kyun dikh raha hai? Redux store start hone ke time pe initialState hi store ke andar chala jata hai.Tumne default me ek todo daal diya tha, isliye wo UI me render ho raha hai.Bas initialState ko empty kar do: todos: [],Real project me initialState ko empty hi rakhte hain.
}



export const todoSlice = createSlice({
    name: 'todo',                  //createSlice me name ek string value hoti hai jo slice ka identifier hota hai.Ye Redux automatically action types generate karte waqt use hota hai.
    initialState,
    reducers: {
        addTodo: (state, action) => {   //Redux slice reducer functions me hamesha do parameters hote hain:state,action
            const todo = {
                id: nanoid(), 
                text: action.payload  //yaha sirf ek hi value arahi hai koi object nhi hai ,and yaha addtodo file me  dispatch(addTodo(input)) hai ye direct value hai so isiliye action.payload.text nhi likh sakte 
            }
            state.todos.push(todo)   
        },
        removeTodo: (state, action) => {
            state.todos = state.todos.filter((todo) => todo.id !== action.payload ) //same here bas id araha hai koi object nhi
        },
         updateTodo:(state,action)=>{
            state.todos=state.todos.map((todo)=> todo.id === action.payload.id ? {...todo,text:action.payload.text} : todo)
            //yaha pura object araha hai, dispatch(updateTodo({ id: todo.id, text: editText })); isiliye  action.payload.text likhn a jaruri hai to identify the correct todo
        }
        // ✅ Redux me replace version
        //  updateTodo: (state, action) => { 
        //     state.todos = state.todos.map((todo) => todo.id === action.payload.id ? action.payload  : todo )  // 👈 pura replace
        // }  // yaha pura todo hi replace hojata but hume bas text change karna tha so woh use kiya ye nhi
    }
})



export const {addTodo, removeTodo,updateTodo} = todoSlice.actions  //Redux Toolkit automatically action creators bana deta hai.todoSlice.actions.addTodo,todoSlice.actions.removeTodo...Yaha tum object destructuring kar rahe ho.Matlab todoSlice.actions se direct ye teen functions nikal liye:

export default todoSlice.reducer

//state → Ye tumhara current slice ka state hai.Redux Toolkit me ye mutable dikh raha hai (like state.todos.push(todo)) kyunki andar hi andar Immer use hota hai jo immutable update me convert kar deta hai.

//action →Ye ek object hota hai jo batata hai ki kya karna hai.Hamesha 2 cheez hoti hai:
// action={
//   type: "todo/addTodo",   // auto generated by slice         type → batata hai ki kaunsa reducer chalna chahiye
//   payload: input          // tumne dispatch ke time bheja      payload → woh data jo state update karne ke liye chahiye
// }
//Isiliye action.payload likh rahe ho, na ki action.payload.text. Agar tum dispatch karte:dispatch(addTodo({ id: 5, text: "hello" }))
//Tab reducer me action.payload.text access karna padta.




// Redux store ek centralized global state provide karta hai. Toh jab page reload nahi hota, ya session chal raha hota hai, Redux state me data rehta hai.

// Lekin:

// Page reload hone pe Redux store reset ho jata hai — isliye agar tum data persist karna chahte ho across page refreshes, tab bhi localStorage ki jarurat padti hai.

// 🔥 Ab Context API me jarurat zyada kyu padti hai?
// Context API me tum khud se state manage kar rahe ho (aur uska update logic).

// Redux Toolkit me middleware, DevTools, persist, and structure zyada powerful hai.

// src/
// ├── components/       # Navbar, Footer, ProductCard
// ├── features/
// │   ├── cart/
// │   │   ├── CartSlice.js
// │   │   └── CartSummary.jsx
// │   └── products/
// │       ├── ProductsSlice.js
// │       └── ProductList.jsx
// ├── pages/            # HomePage, ProductPage, CartPage
// ├── redux/            # store.js
// ├── services/         # productApi.js, cartApi.js
// └── utils/            # formatCurrency.js, validation.js


// Explanation:

// components/ → Reusable dumb UI components (buttons, modals, cards, forms).

// features/ → Feature-based foldering with Redux slice + UI (good for large apps).

// pages/ → Route-based pages (Home, Login, Dashboard).

// redux/ → Store setup, middleware, persistConfig, etc.
 
// hooks/ → Custom React hooks (like useFetch, useAuth).

// services/ → API logic, backend integration, business logic.

// layouts/ → Common layout wrappers (header + sidebar + footer).

// utils/ → Helper functions (date formatting, validation, constants).

// assets/ → Static files (images, fonts, icons).







// 🔹 Context API (Manual kaam)
// 👉 Context me tumko khud sab handle karna padta hai
// Matlab: State update karna hai → khud new object banana padega, Purana state directly change nahi kar sakte ❌
// Simple line: 👉 “Context me tum khud copy bana ke update karte ho”

// 🔥 Example (Without Immer – Context)
// setTodos(prev =>
//   prev.map(todo =>
//     todo.id === id
//       ? { ...todo, text: "new" }  // 👈 khud copy banayi object ki uske andhr sab dala .. 
//       : todo
//   )
// )

// 👉 Yaha tum: copy bana rahe ho, manually update kar rahe ho

// reason:
// const addTodo = (todo) => {
//   setTodos((prev) => prev.push(todo))        -> setTodos(4)   todos banjaega number ,original array change karta hai ❌
// }
// Direct mutation ho raha hai❌ prev.push(todo) 👉 Tum original state ko change kar rahe ho 👉 React me ye allowed nahi hai
// 💣 Result kya hoga? 👉 todos ban jayega number 😵 👉 UI break ho jayega



// 👉 Immer ek library hai jo: immutable state ko easy bana deti hai
// Simple language:
// 👉 Normally: state ko directly change nahi kar sakte ❌ copy bana ke change karna padta hai 😅
// 👉 Immer kya karta hai: tumhe lagta hai tum direct change kar rahe ho ,but actually wo andar se copy bana deta hai ✅

// 🔥 Example (With Immer – Redux Toolkit)

// state.todos.push(newTodo) -> hume Lagta hai galat hai (mutation) but 👉 Immer behind the scenes:
// // internally kuch aisa hota hai
// copy = [...state.todos]
// copy.push(newTodo)
// return copy



// QUESTION :- 
// let state = {
//   todos: [12, 33]
// }
// let final = state.todos.push(44)

// console.log(final, state)  //->3 {todos: [12, 33, 44]}    ✔ Array update ho gaya ✔ push kaam kar raha hai

// 🤔 toh fhir uper isme-=> state.todos.push(newTodo) kya prblm thi jo immer use ho rha hai 
// 👉 JS me koi problem nahi hai 👉 Problem hai React / Redux ke rules me
// 🔥 Core Issue = Mutation vs Immutability
// 🟥 Mutation (Galat in React/Redux) 👉 Original data ko directly change karna
// 🟩 Immutability (Correct way)👉 Original data ko touch nahi karte, new copy banate hain

// state.todos.push(44) 👉 Direct original state change ❌
// ⚠️ React / Redux ko kya chahiye? 👉 NEW reference (new object / new array)

// React compare karta hai:  oldState === newState
// ❌ Tumhara case (mutation) state.todos.push(44)  👉 same array modify hua 👉 reference same hai
// oldTodos === newTodos  // true ❌

// 👉 React bolega: “kuch change hi nahi hua”


// ✅ Correct way (immutable) 
// copy = [...state.todos] 
// copy.push(44)
// 👉 new array bana: oldTodos === newTodos  // false ✅
// 👉 React bolega: “haan change hua hai → re-render karo”

// 🔥 Redux ka golden rule: 👉 “Never mutate state directly”

// so should be use mutating method in react?
// 👉 Mutating methods likh sakte ho
// ❌ But React state pe direct use nahi karna
// 👉 Local variable pe → OK ✅
// 👉 State pe → NOT OK ❌

// Redux Toolkit exception









// ⚡ Redux me allowed kyu hai? 👉 Redux Toolkit internally Immer use karta hai
// Isliye: state.todos.push(todo)  // ✅ allowed
// 👉 Ye actually safe hai because: Immer copy banata hai, original state safe rehta hai
// newState = {
//   ...state,
//   todos: [...state.todos, 44]
// }copy banayi ✅safe update kiya ✅new reference diya ✅






// 🔹 Redux Toolkit (Automatic kaam)
// 👉 Redux Toolkit me ek library use hoti hai: Immer 👉 Ye tumhara kaam easy kar deta hai

// Tum aise likhte ho: todo.text = "new" 😳 Lagta hai direct change kar rahe ho BUT ❗
// 👉 Actually background me: copy banti hai, safe update hota hai

// Simple line: 👉 “Redux Toolkit me tum direct change jaisa likhte ho, but andar se safe copy ban jati hai”



// 👉 Context = manual update (khud copy banao)
// 👉 Redux Toolkit = automatic update (Immer copy bana deta hai)


